### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by bosssyyyy** [jebbyk/OSBES-minecraft-bedrock-edition-shader#1]
I hope to add raindrop noise and some reflections to the ground in rainy days, and reduce the area of accumulated water on the ground.In addition, I hope you can split files according to their functions, which is more conducive to reading and modifying. (Software translation)

**Comment by jebbyk** [comment]
Ok, I will split it later. So if you wanna contribute you will be able to do this via Pull Request
