### ISSUE TITLE
Why are there so many dead branches?

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#101]
Might be a good idea to delete the already merged ones. Having them all there makes it kind of annoying to navigate, and there isn't really a reason for them to be kept around
![image](https://user-images.githubusercontent.com/48618519/112979155-1c1ce900-9150-11eb-82c5-f05f3f6319d6.png)

**Comment by OpenSauce04** [comment]
`master` in particular has absolutely no reason to exist, as it was functionally replaced by the `develop` branch

**Comment by jebbyk** [comment]
ye agreed
