### ISSUE TITLE
Issue OSBES Shader, Cloud texture

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#103]
Clouds are uneven in texture while moving across sky. May affect reflections? Please fix this bug! Thx!

**Comment by jebbyk** [comment]
@samlovesgithub Hi. can you please tell me what is your device and please show me a screenshot of the issue :-)

**Comment by samlovesgithub** [comment]
Sure! I will take a screenshot of my device!
![image](https://user-images.githubusercontent.com/81644438/113375289-12a4a400-933d-11eb-992f-e336b12bc6bb.jpeg)

**Comment by jebbyk** [comment]
@samlovesgithub  oh, apple... so please check an issue #72. if it looks the same as yours I'll close it as a duplicate

**Comment by samlovesgithub** [comment]
Yep the exact same issue! And the exact same device! Thanks!

**Comment by jebbyk** [comment]
ok than, duplicate
