### ISSUE TITLE
Water textures on android

### ISSUE THREAD

**Issue by INFIERNOXIII** [jebbyk/OSBES-minecraft-bedrock-edition-shader#104]
Hi thanks for your amazing shader i noticed this issue about the water.
- last minecraft version on android
- device samsung galaxy S8
- your last release
- i dont use any texture pack/other shader

![Screenshot_20210330-233717_Minecraft](https://user-images.githubusercontent.com/74121661/113062772-8f584680-91b4-11eb-8c53-0d42ec230b9c.jpg)
![Screenshot_20210330-233653_Minecraft](https://user-images.githubusercontent.com/74121661/113062779-91220a00-91b4-11eb-968c-8c84e7240c7b.jpg)

**Comment by jebbyk** [comment]
@random-tester83 Hi. can you pls tell me what is exactly wrong? it is all seems fine to me on your screenshots

**Comment by INFIERNOXIII** [comment]
The white lines on the water idk if its just an effect or a bug but for me its look like very wired

**Comment by INFIERNOXIII** [comment]
Probabaly a light effect idk

![Screenshot_20210331-044755_Minecraft](https://user-images.githubusercontent.com/74121661/113083376-651a7f00-91dc-11eb-9fd3-7706578809d5.jpg)
![Screenshot_20210331-044725_Minecraft](https://user-images.githubusercontent.com/74121661/113083379-66e44280-91dc-11eb-85da-ae1ba6c56a90.jpg)

**Comment by jebbyk** [comment]
it is not quite a bug. but probably some tweaking may improve it

**Comment by INFIERNOXIII** [comment]
ok thnx

**Comment by OpenSauce04** [comment]
Basically what's happening here is that the glimmer from the top of the water is being *stretched* down to the bottom of the next bit of water
Kinda like this (excuse the bad diagram)
![image](https://user-images.githubusercontent.com/48618519/113916440-e1622300-97d7-11eb-80d6-a32d022d1897.png)
So yes, this is a bug

**Comment by jebbyk** [comment]
maybe it is but in some cases it looks cool IMO.

**Comment by OpenSauce04** [comment]
Yeah with the new water normals and the texture correction I have PR'd (#143) it looks much better than before. Should be left in
