### ISSUE TITLE
Head items not loading texture correctly

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#107]
![20FBE35D-3095-4684-910F-10DB747F4E5A](https://user-images.githubusercontent.com/81644438/113327586-26261f80-92e9-11eb-8948-26f79fef35fe.jpeg)

**Comment by jebbyk** [comment]
can you please explain what is wrong here :-)?

**Comment by samlovesgithub** [comment]
Yes Mr Jebbyk, the head items do not render properly in the inventory. There is missing texture. I am sorry that the picture is cut off!

**Comment by jebbyk** [comment]
ok thank you I'll check it

**Comment by OpenSauce04** [comment]
Here's a better image showing this issue
![image](https://user-images.githubusercontent.com/48618519/115548807-cbf0fc80-a29f-11eb-85b7-f2b909b0b14b.png)

**Comment by jebbyk** [comment]
ty :-)

**Comment by jebbyk** [comment]
probably fixed in 0.13.1
