### ISSUE TITLE
Critical bug, Underwater light effect briefly and occasionally stops working

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#109]
When moving in water and placing blocks, the light rays underwater do not load occasionally,

![28ED00C9-BCE9-421B-8B12-4B58602A3740](https://user-images.githubusercontent.com/81644438/113327826-6a192480-92e9-11eb-934a-7a168b6511cd.jpeg)

**Comment by jebbyk** [comment]
it happens not quite frequently. so I put not critical label

**Comment by jebbyk** [comment]
btw it is a duplicate
