### ISSUE TITLE
Direct horizontal Reflection in ice is odd?

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#111]
![image](https://user-images.githubusercontent.com/81644438/113354345-0c96cf00-930d-11eb-8ad0-59376fd869d3.png)

The reflection in ice looks weird, please try to remove?

**Comment by jebbyk** [comment]
@samlovesgithub how should it look in your opinion?

**Comment by samlovesgithub** [comment]
I believe it should be removed or rendered as a flat polygon light source. Not a circle. But it's actually okay if you decide to keep it.

**Comment by jebbyk** [comment]
I think I'll just make it a bit less shiny

**Comment by samlovesgithub** [comment]
That is a clever idea! Maybe increase anti aliasing? Or turn down brightness for that light source? IDRK shading code stuff! I'm sure you'll fix it wonderfully!

**Comment by OpenSauce04** [comment]
Circles in Minecraft. enough said

**Comment by OpenSauce04** [comment]
This isn't just ice, this actually happens (to a lesser extent) with most reflective blocks when very close. I think the only reason why it looks weird is the _really_ bad colour banding on the reflection, which can probably be fixed
(Zoom in to see)
![Screenshot_20210422-075939_Minecraft.jpg](https://user-images.githubusercontent.com/48618519/115669987-d44d4400-a340-11eb-9261-5586fa5e759c.jpg)
![Screenshot_20210422-075926_Minecraft.jpg](https://user-images.githubusercontent.com/48618519/115670001-d7483480-a340-11eb-877a-e9ab28c635e3.jpg)

**Comment by jebbyk** [comment]
main light dirrectiosn was changed. And also it is now controlled by preset settings
