### ISSUE TITLE
End stone texture bugged(Time: Midnight)

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#112]
![image](https://user-images.githubusercontent.com/81644438/113360925-c5164000-9318-11eb-911a-01a600cc3d1e.jpeg)

**Comment by jebbyk** [comment]
@samlovesgithub  Hi. it doesn't looks broken on a screenshot. can you record a video please :-)?

**Comment by samlovesgithub** [comment]
I actually looked back at the end stone rendering in game. It doesn't seems to be a bug or issue and it doesn't look as bad as I had thought! No problem here!

**Comment by jebbyk** [comment]
ok than
