### ISSUE TITLE
When submerged in lava, there seems to be a visual bug?

### ISSUE THREAD

**Issue by samlovesgithub** [jebbyk/OSBES-minecraft-bedrock-edition-shader#116]
![image](https://user-images.githubusercontent.com/81644438/113448428-d2d7ce00-93c9-11eb-8fe4-6f6cfb1ced91.jpeg)

**Comment by INFIERNOXIII** [comment]
I got it too :

- device : samasung S10+ exynos9820
- android 11
- official minecraft V1.16.210
- shaders version 0.12.3a

![Screenshot_20210404-085418_Minecraft](https://user-images.githubusercontent.com/74121661/113501123-6d97f000-9523-11eb-80c1-159182c92f7e.jpg)

**Comment by jebbyk** [comment]
probably fixeed
