### ISSUE TITLE
Unused textures

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#119]
The amount of textures that are completely identical to the vanilla equivalent is absolutely insane
I removed all of them, and the size of the pack more than **halved** and the loading speed increased *significantly*
The issue is that removing these files (most notably the `entity` and `items` folders) messes with the texture atlas in a way that causes the pack to act in strange ways when attempting to draw water as well as certain blocks
Is there any feasible way that we can remove those textures while still keeping the pack stable?
I think the payoff would be worth the effort

**Comment by jebbyk** [comment]
have no idea how entities textures can affect water btw

**Comment by OpenSauce04** [comment]
Yeah I'm not sure either

**Comment by jebbyk** [comment]
texture pack is separed in 0.13.1
