### ISSUE TITLE
Minecart View Bug

### ISSUE THREAD

**Issue by GomerGit** [jebbyk/OSBES-minecraft-bedrock-edition-shader#123]
When looking up/back while riding minecart on First Person view, seems that the player view is messed up. 

![Screenshot_20210406_111538_com huawei himovie overseas](https://user-images.githubusercontent.com/63869057/113653988-71fe0d80-96c9-11eb-9dd2-5d3038bee8a8.jpg)

**Comment by jebbyk** [comment]
@GomerGit Hi, can you please record a video of this issue. Probably it is not related to the OSBES itself

**Comment by GomerGit** [comment]
>

**Comment by GomerGit** [comment]
https://user-images.githubusercontent.com/63869057/113715342-faa59980-971b-11eb-9ffe-96c88dc0e7de.mp4

This only happens when i use OSBES.

**Comment by jebbyk** [comment]
wow. Have no idea what is going on with player view. But rails are strange and it is 100% related to OSBES

**Comment by xKingDark** [comment]
Its minecraft related!, if you remove the shader it will still happens!

**Comment by OpenSauce04** [comment]
Yeah that doesn't seem like something the shader would even be able to control if we tried, so that's likely not related.
Although the rail thing is definitely a bug

**Comment by jebbyk** [comment]
probably was fixed in later OSBES versions
