### ISSUE TITLE
Water and Clouds issue

### ISSUE THREAD

**Issue by Kimlerk** [jebbyk/OSBES-minecraft-bedrock-edition-shader#128]
![6B9B01BA-15D0-4915-9199-F061C6D1ACD5](https://user-images.githubusercontent.com/82212871/114168796-5ce5e080-994e-11eb-9804-3b8ee428642c.png)
![B3C12EEA-9012-45B3-AB05-835AFD340D0B](https://user-images.githubusercontent.com/82212871/114168813-640cee80-994e-11eb-8a55-4a833f829dce.png)

JebbyK,
Water has weird black texture. Wasn’t there when I had the 0.11 versions. Only started in 0.12 versions. Clouds have both vanilla and osbes merged ever since. 
Thank you

**Comment by Kimlerk** [comment]
Edit: devices used (all devices had same issue)
Samsung M20, iPhone 7 and SE2, iPad 4

**Comment by jebbyk** [comment]
@Kimlerk are you sure Samsung has this cloud bug?

**Comment by jebbyk** [comment]
no responce from author
