### ISSUE TITLE
Versioning inconsistency

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#137]
I think we should drop the `a` at the end of all of the versions
It doesn't really add anything, isn't even used half the time, and there has never even been a `b` version

**Comment by jebbyk** [comment]
alpha -> beta -> release. Isn't it?

**Comment by OpenSauce04** [comment]
> alpha -> beta -> release. Isn't it?

But these aren't alphas though right? These are releases. (even if they are early ones)

**Comment by OpenSauce04** [comment]
The only reason why Minecraft used "alpha" and "beta" labels on it's releases is because every time it went to a new development stage, they started again at `1.0`, for example they went from `alpha 1.2.6` to `beta 1.0`
OSBES does no such thing

**Comment by jebbyk** [comment]
:-) 
![image](https://user-images.githubusercontent.com/40975486/116520593-beb5bc80-a8f4-11eb-9319-35df3befb191.png)

**Comment by OpenSauce04** [comment]
> :-) 
> ![image](https://user-images.githubusercontent.com/40975486/116520593-beb5bc80-a8f4-11eb-9319-35df3befb191.png)
> 

Yeah we are in alpha stage, but it doesn't need to be on the version number.
Besides, whether or not it even is on the version number is so inconsistent

**Comment by OpenSauce04** [comment]
Some examples:

![Screenshot_20210429-121929_GitHub.jpg](https://user-images.githubusercontent.com/48618519/116543205-80fd6780-a8e5-11eb-898e-8104e660c4ab.jpg)
![Screenshot_20210429-121956_GitHub.jpg](https://user-images.githubusercontent.com/48618519/116543216-83f85800-a8e5-11eb-8181-03edb130febb.jpg)
![Screenshot_20210429-122020_GitHub.jpg](https://user-images.githubusercontent.com/48618519/116543225-865ab200-a8e5-11eb-943a-5f659e3102a3.jpg)
![Screenshot_20210429-122117_GitHub.jpg](https://user-images.githubusercontent.com/48618519/116543235-8a86cf80-a8e5-11eb-8495-4e1ac3814691.jpg)
![Screenshot_20210429-122100_GitHub.jpg](https://user-images.githubusercontent.com/48618519/116543242-8c509300-a8e5-11eb-89d4-259e11077685.jpg)
![Screenshot_20210429-122358_Discord.jpg](https://user-images.githubusercontent.com/48618519/116543450-c9b52080-a8e5-11eb-84c9-6fa18532431c.jpg)

Either go all or nothing

**Comment by OpenSauce04** [comment]
Also for some reason the link for downloading directly from the repo is called "alpha" in the #info channel, which is just wrong

**Comment by OpenSauce04** [comment]
The main reason why I'm asking for this to change is because a lot of developers use letters to signify hotfixes
From the next release onwards that is, no point in renaming previous versions

**Comment by jebbyk** [comment]
no more "a" in versions
