### ISSUE TITLE
Gold and coal ores are impossible to differentiate from one another in certain light conditions

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#142]
Some of these are gold and some of these are coal
![image](https://user-images.githubusercontent.com/48618519/116783314-fdc74780-aa85-11eb-817b-3b75cf5c223e.png)

**Comment by OpenSauce04** [comment]
This is gold appariently
![Screenshot from 2021-05-01 15-07-57](https://user-images.githubusercontent.com/48618519/116783458-c73dfc80-aa86-11eb-867f-6c74874b42c3.png)

**Comment by OpenSauce04** [comment]
@jebbyk should we move this issue to the PBR pack repo?

**Comment by jebbyk** [comment]
should be ok rn. Can be controlled by texture pack.
