### ISSUE TITLE
While in education editon world textures are wonky 

### ISSUE THREAD

**Issue by ghost** [jebbyk/OSBES-minecraft-bedrock-edition-shader#145]
When on a education edition world( the slider in settings of normal bedrock edition) most textures will be wonky. Some times dirt will even show ore textures. I am on mobile. It appears to be some what random because some times sand works fine some times not. Same thing for dirt which seems to only show correctly under ground.

![Screenshot_20210504-181157_Minecraft](https://user-images.githubusercontent.com/83675620/117080986-8b17cf80-ad04-11eb-9391-56415182d3e7.jpg)
![Screenshot_20210504-181058_Minecraft](https://user-images.githubusercontent.com/83675620/117080989-8c48fc80-ad04-11eb-94c4-62ee092943e6.jpg)
![Screenshot_20210504-181115_Minecraft](https://user-images.githubusercontent.com/83675620/117080990-8e12c000-ad04-11eb-8bb5-2d0339a72a2d.jpg)

**Comment by OpenSauce04** [comment]
Education edition and experimental features are not supported by OSBES

**Comment by jebbyk** [comment]
I will check and add new textures ASAP

**Comment by jebbyk** [comment]
this issue is probably fixed in 0.13.1
