### ISSUE TITLE
Ore Duplication Mod

### ISSUE THREAD

**Issue by BrokenPencil514** [jebbyk/OSBES-minecraft-bedrock-edition-shader#147]
I added the ore duplication mod along with this shader and it did this to the world.

![574D42B9-0345-42A3-96A9-D3B2E627FB71](https://user-images.githubusercontent.com/83703901/117133817-5cccdb00-ad6a-11eb-9bd8-b3e81447cd0c.png)

**Comment by OpenSauce04** [comment]
Anything that adds block textures breaks the shader for the same reason that Education Edition does. Does this add any?

**Comment by jebbyk** [comment]
OSBES 0.13.1 should now normally support addons
