### ISSUE TITLE
When will the update to 0.13 be completed?

### ISSUE THREAD

**Issue by zeng-zeng367** [jebbyk/OSBES-minecraft-bedrock-edition-shader#149]
I hope the water can look better. I don’t like 0.12 water myself.

**Comment by OpenSauce04** [comment]
Not sure about an ETA, but a lot of minor changes for 0.13 have already been completed
You'll be glad to know that one of these changes is an adjustment to water, which looks _much_ nicer than before

**Comment by IRULWNL** [comment]
Pls remove texture pack.only shader

**Comment by ghost** [comment]
@IRULWNL 

This is currently impossible based on how this shader works.

**Comment by OpenSauce04** [comment]
> Pls remove texture pack.only shader

For now we can't really do that, although later down the line texture pack support will be better

**Comment by zeng-zeng367** [comment]
Can I see the progress of your current shaders?

**Comment by Darthveder69420** [comment]
> > Pls remove texture pack.only shader
> 
> For now we can't really do that, although later down the line texture pack support will be better

Will it fix the shader not working on iPad mini 5. If you don’t know about it, it’s basically if you select the shader in global resource or world options it does not work and crashes the game. No its not that I used any kind of texture pack.

**Comment by jebbyk** [comment]
I don't think mc  crashes are some how related to osbes

**Comment by jebbyk** [comment]
0.13.1 is ready and 0.13.2 is comming soon
