### ISSUE TITLE
OSBES Corrupted In Servers And Local worlds With No Texture Block

### ISSUE THREAD

**Issue by LeonetKenner** [jebbyk/OSBES-minecraft-bedrock-edition-shader#155]
The OSBES Texture showing weired corrupted textures and lines on blocks
## Expected Behavior
I thought it would Actually Work But No luck

## Current Behavior
The OSBES Texture showing weired corrupted textures and lines on blocks

## Steps to Reproduce
No link needed its basically the same thing
But i think development release

**Comment by LeonetKenner** [comment]
![Screenshot 2021-05-19 190144](https://user-images.githubusercontent.com/84083235/118821272-b4c02180-b8d4-11eb-936e-db5b147bfbce.png)

**Comment by OpenSauce04** [comment]
Windows 10 isn't supported for now due to an issue with the bedrock engine as a whole, sorry!

**Comment by jebbyk** [comment]
windows 10 is not currently supported. You can go here and ask mojang for supporting shaders https://feedback.minecraft.net/hc/en-us/community/posts/360077420452-3rd-party-shader-support-for-render-dragon
