### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by Demon-Ak** [jebbyk/OSBES-minecraft-bedrock-edition-shader#156]

**Comment by jebbyk** [comment]
@Demon-Ak  what is your problem? :-)

**Comment by OpenSauce04** [comment]
> 
> 
> @Demon-Ak what is your problem? :-)

Probably spam like that other guy

**Comment by Demon-Ak** [comment]
Am sorry am back my... I already said my problem

**Comment by Demon-Ak** [comment]
Am sorry I did another mistake by editing the essue

**Comment by Demon-Ak** [comment]
So my problem is that when I open the inventory 
I find all the blocks icons glitched and you can't know which block that you have chose till you place it in the world

**Comment by Demon-Ak** [comment]
![Uploading Screenshot_2021-05-25-15-05-41-404_com.mojang.minecraftpe.jpg…]()

**Comment by Demon-Ak** [comment]
This is an example

**Comment by Demon-Ak** [comment]
Am going to send the essue in 3 days so I make sure to read it
