### ISSUE TITLE
Glitchy blocks

### ISSUE THREAD

**Issue by AverageCrafter** [jebbyk/OSBES-minecraft-bedrock-edition-shader#160]
## Expected Behavior
 Water Texture is ruined and New users are complaining.

## Current Behavior
 Some blocks are super glitched, even when placed down.

**Comment by AverageCrafter** [comment]
There's some blocks that have been glitched since the 1.17 update, the blocks that are gliched are The Anvil, Polished Deepslate, Andesite, and the Acacia plank. An example for the issue. 

![Screenshot_20210622-204025_Minecraft](https://user-images.githubusercontent.com/85814724/123021813-62be6000-d39a-11eb-8a62-e9a39533a3f2.jpg)
![Screenshot_20210622-204038_Minecraft](https://user-images.githubusercontent.com/85814724/123021829-67831400-d39a-11eb-9fa4-d8e6e343954b.jpg)
![Screenshot_20210622-204055_Minecraft](https://user-images.githubusercontent.com/85814724/123021836-6ce05e80-d39a-11eb-8320-99669f4a0b6d.jpg)
![Screenshot_20210622-204001_Minecraft](https://user-images.githubusercontent.com/85814724/123021775-533f1700-d39a-11eb-9e35-013a45ab3a3d.jpg)
![Screenshot_20210622-204015_Minecraft](https://user-images.githubusercontent.com/85814724/123021803-5f2ad900-d39a-11eb-8764-f16dfc4c944d.jpg)

**Comment by GonzoStudioz** [comment]
I experience this too! There are even more broken blocks! All amethyst is broken ancient debris is broken and tinted glass is broken

**Comment by AverageCrafter** [comment]
> I experience this too! There are even more broken blocks! All amethyst is broken ancient debris is broken and tinted glass is broken

The water has no texture, and the textures look off. Ever since the 1.17 update

**Comment by AverageCrafter** [comment]
An example for the textures

![Screenshot_20210622-204025_Minecraft](https://user-images.githubusercontent.com/85814724/123021813-62be6000-d39a-11eb-8a62-e9a39533a3f2.jpg)
![Screenshot_20210622-204038_Minecraft](https://user-images.githubusercontent.com/85814724/123021829-67831400-d39a-11eb-9fa4-d8e6e343954b.jpg)
![Screenshot_20210622-204055_Minecraft](https://user-images.githubusercontent.com/85814724/123021836-6ce05e80-d39a-11eb-8320-99669f4a0b6d.jpg)
![Screenshot_20210622-204001_Minecraft](https://user-images.githubusercontent.com/85814724/123021775-533f1700-d39a-11eb-9e35-013a45ab3a3d.jpg)
![Screenshot_20210622-204015_Minecraft](https://user-images.githubusercontent.com/85814724/123021803-5f2ad900-d39a-11eb-8764-f16dfc4c944d.jpg)

**Comment by AverageCrafter** [comment]
I know it is very hard to fix problems but this is really "buggin" me

**Comment by jebbyk** [comment]
it is a 1.17.xx release, right? not a beta?

**Comment by jebbyk** [comment]
this issue is probably fixed in 0.13.1
