### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by GonzoStudioz** [jebbyk/OSBES-minecraft-bedrock-edition-shader#164]
The textures are broken and the water is not as detailed as images show. 

## Expected Behavior
 What should happen is the textures should stay correct and not be ugly. The water should be more detailed

## Current Behavior
 The water and textures are broken

**Comment by johnpaulkun** [comment]
Can't see anything except the sky
![Uploading Screenshot_20210705-040114.png…]()

**Comment by jebbyk** [comment]
@johnpaulkun can you reupload your screenshot please

**Comment by jebbyk** [comment]
textures problem is probably fixed in 0.13.1.
