### ISSUE TITLE
Not working in 1.17

### ISSUE THREAD

**Issue by Jaskarangill85** [jebbyk/OSBES-minecraft-bedrock-edition-shader#167]
## Expected Behavior
on 24th june i downloaded the latest version of osbes shader for mcpe 1.17.0 when i applied it after loading my screen get white no controls or hud where appear but when i tap on screen i can controll but cant see anything.

## Current Behavior
i have samsung galaxy m21 with exynos 9611 and 4gb ram with android 11

**Comment by OpenSauce04** [comment]
This is already a known issue

**Comment by jebbyk** [comment]
@OpenSauce04  are you sure about this?

**Comment by OpenSauce04** [comment]
@jebbyk I must have thought I was replying to something else I read on the discord because so many people use just "not working" as the title, I hadn't actually read about this before
Will delete that comment :P

**Comment by Darthveder69420** [comment]
Pretty sure this was fixed.

**Comment by jebbyk** [comment]
@Jaskarangill85 Can you please try the latest OSBES 0.13.2 and tell me if it still not working?

**Comment by jebbyk** [comment]
Old issue. No answer. Probably fixed. closed
