### ISSUE TITLE
Hey can you help me

### ISSUE THREAD

**Issue by kedrick021** [jebbyk/OSBES-minecraft-bedrock-edition-shader#171]
Are you the one ho make shader for open4es chocapic shader the new  view code ?

Why sky half are white 
![Screenshot_2021-06-27-17-27-47-300_org videolan vlc](https://user-images.githubusercontent.com/76839710/123540937-20b76480-d774-11eb-8656-26841d536ab4.jpg)

![Screenshot_2021-06-27-17-28-07-113_org videolan vlc](https://user-images.githubusercontent.com/76839710/123540942-2614af00-d774-11eb-9d56-008626d5fa00.jpg)

I try to change the white sky to blue but half are white
Plsss help

**Comment by jebbyk** [comment]
this repository related only to OSBES. Please create an issue in Open4es repository :-)
