### ISSUE TITLE
Daylight coloring 

### ISSUE THREAD

**Issue by scihi** [jebbyk/OSBES-minecraft-bedrock-edition-shader#178]
The daylight color is too yellowish which gives a feeling of sunrise and sunset
Can you please lower down the yellow intensity and increase the blue intensity.

**Comment by zeng-zeng367** [comment]
But I like the yellow temperature

**Comment by jebbyk** [comment]
@scihi can you please send me some screenshots?

**Comment by scihi** [comment]
![Uploading Screenshot_20210630-202538_Minecraft.jpg…]()

**Comment by scihi** [comment]
![Uploading Screenshot_20210630-202554_Minecraft.jpg…]()

**Comment by scihi** [comment]
![Uploading Screenshot_20210630-202615_Minecraft.jpg…]()

**Comment by scihi** [comment]
![Screenshot_20210630-202615_Minecraft](https://user-images.githubusercontent.com/83114809/123984240-19958e00-d9e2-11eb-8eb7-25d6e0282a4f.jpg)

**Comment by scihi** [comment]
![Screenshot_20210630-202554_Minecraft](https://user-images.githubusercontent.com/83114809/123984316-287c4080-d9e2-11eb-975a-c3fb776bb8b0.jpg)

**Comment by scihi** [comment]
![Screenshot_20210630-202538_Minecraft](https://user-images.githubusercontent.com/83114809/123984407-3c27a700-d9e2-11eb-834b-037523538393.jpg)

**Comment by jebbyk** [comment]
It would be possible to change with presets

**Comment by scihi** [comment]
What is presets

**Comment by jebbyk** [comment]
@scihi starting from OSBES v0.13.1 you are able to change some parameters of this shader in /shaders/glsl/includes/options/preset folder.
