### ISSUE TITLE
Not working in 1.17

### ISSUE THREAD

**Issue by Abdullah2008200** [jebbyk/OSBES-minecraft-bedrock-edition-shader#179]
A lot of blocks like andesite,anvils,ladders and all kinds of rails are glitched and not completed

there’s no water resource pack or raining

the shader was really awesome and I was very satisfied until 1.17 came🥲

pls fix your shader😍❤️

**Comment by OpenSauce04** [comment]
The shader hasn't even been updated for 1.17
Wait until then
