### ISSUE TITLE
0.13.1 not working properly for 1.17 in iPad mini 5th gen

### ISSUE THREAD

**Issue by Darthveder69420** [jebbyk/OSBES-minecraft-bedrock-edition-shader#181]
Everything except for the water, sky, sun and mobs is black
## Expected Behavior

The shader should work properly
## Current Behavior

Shit happened and it won’t work properly

gonna provide a screenshot p
![Uploading 8ED033C3-AF8C-4457-B1CE-BDFB118503FF.png…]()

**Comment by Darthveder69420** [comment]
Ight it works now so nevermind

**Comment by FoxxeyPlays** [comment]
Wait how did you fix it? Same thing is happening to me

**Comment by Darthveder69420** [comment]
I deleted pre release and installed release and It also doesn’t seem to work with 1.16 worlds in 1.17

**Comment by FoxxeyPlays** [comment]
K thanks
