### ISSUE TITLE
0.13.1 not working in 1.17 for iPhone 7

### ISSUE THREAD

**Issue by FoxxeyPlays** [jebbyk/OSBES-minecraft-bedrock-edition-shader#182]
## Expected Behavior

Shader should work correctly 
## Current Behavior

All blocks are black

**Comment by OpenSauce04** [comment]
Screenshots? -_-

**Comment by FoxxeyPlays** [comment]
Sorry 
![059DC607-3DB5-473B-B3CE-74FCED03BF16](https://user-images.githubusercontent.com/86932123/124400252-130f5b00-dcef-11eb-8bd2-8aa043975a87.png)
![A09F32E2-3380-4D4D-815C-0FF800FFA38D](https://user-images.githubusercontent.com/86932123/124400254-13a7f180-dcef-11eb-958a-8a5b5b797aa1.png)

**Comment by jebbyk** [comment]
wow

**Comment by FoxxeyPlays** [comment]
Ok so I used the pbr with it and it’s not black but it’s still broken

**Comment by FoxxeyPlays** [comment]
![1C0C3FA5-9828-41D1-B871-8FB0C776D0A9](https://user-images.githubusercontent.com/86932123/124677442-797eaf80-de8e-11eb-9698-f0d99c65bb1f.png)

**Comment by jebbyk** [comment]
@FoxxeyPlays What is the version of minecraft on your screenshot? There is two versions of Vanilla Normals Renewed for bedrock. Probably you've downloaded VNR for betas while playing minecraft release version.

![image](https://user-images.githubusercontent.com/40975486/124695420-f77d9d80-df04-11eb-8ab3-26be307c863a.png)
try first one, and if it does not work try second one :-) 
Dont forget to close minecraft and open it again after applying texturepack.

**Comment by makakam83** [comment]
It looks exactly the same as on the second screenshot above on my galaxy s10e..

**Comment by FoxxeyPlays** [comment]
1.17.2 I think. I haven’t messed with any settings or anything so probably the latest version.

**Comment by FoxxeyPlays** [comment]
I tried it again and I reloaded Minecraft this time, which I didn’t do before, but the textures were still glitched

**Comment by FoxxeyPlays** [comment]
Does it matter if the pbr is on top or below the shader? I’ve been putting it on top

**Comment by FoxxeyPlays** [comment]
Ok well uhhhh I just took the pbr off and it randomly decided to work but the textures are downscaled now

**Comment by FoxxeyPlays** [comment]
![Uploading 69D5D10F-0E36-4A61-9942-F489C872007B.png…]()

**Comment by FoxxeyPlays** [comment]
![Uploading 81EA1D56-5711-4980-B46C-385A4EFEFD9B.png…]()

**Comment by FoxxeyPlays** [comment]
And now it’s black again……….

**Comment by makakam83** [comment]
My galaxy s10e displayed it just like your second screenshot until I put the pbr textures on top. Now it is working ok. 

Btw
@jebbyk what can I do to make it work on my bedrock server? For now it works only offline.

**Comment by FoxxeyPlays** [comment]
That’s weird because it did the same thing for me whether I put it on top or below

**Comment by FoxxeyPlays** [comment]
The closest thing I can get to it working is without the pbr but the textures are downscaled so idrk

**Comment by ChaseBuccaran** [comment]
I've tried to download both VNR but it keeps saying that both failed to download.

**Comment by FoxxeyPlays** [comment]
@ChaseBuccaran Same but when I manually installed it it worked fine. Just download iZip, and share the file to it, rename it to .zip, then .mcpack and open it in Minecraft and it will work I think.

**Comment by jebbyk** [comment]
black blocks issue is fixed in 0.13.2
