### ISSUE TITLE
The sun is too big

### ISSUE THREAD

**Issue by zeng-zeng367** [jebbyk/OSBES-minecraft-bedrock-edition-shader#186]
I think the sun looks too big and not beautiful
![Screenshot_2021-07-08-12-10-13-266_com mojang minecraftpe](https://user-images.githubusercontent.com/81863795/124861184-9bd71100-dfe5-11eb-86c7-a323b9f11f37.jpg)

**Comment by jebbyk** [comment]
thanks

**Comment by jebbyk** [comment]
fixed in 0.13.2
