### ISSUE TITLE
How to apply vanilla accurate the PBR texture pack in 0.13.1

### ISSUE THREAD

**Issue by LANCECRAFT1104** [jebbyk/OSBES-minecraft-bedrock-edition-shader#187]
## Expected Behavior

I expected vanilla accurate PBR can run on 0.13.1, but it doesn't work.
## Current Behavior

![Screenshot_2021-07-09-12-04-06-50](https://user-images.githubusercontent.com/75970303/125022277-e2447280-e0ae-11eb-8641-b183e0e0a8cf.png)

## Steps to Reproduce

![Screenshot_2021-07-09-12-03-04-32](https://user-images.githubusercontent.com/75970303/125022293-ed979e00-e0ae-11eb-8105-2f0b818723f7.png)
Download .mcpack file

Open it with minecraft

Select this shader pack in settings

Place PBR texture pack on top of OSBES

**Comment by LANCECRAFT1104** [comment]
Teach me how to apply PBR on the latest version.

**Comment by LANCECRAFT1104** [comment]
I put vanilla accurate PBR on top of OSBES but all blocks are crazy.

**Comment by LANCECRAFT1104** [comment]
![Screenshot_2021-07-09-12-03-04-32](https://user-images.githubusercontent.com/75970303/125021838-fdfb4900-e0ad-11eb-82f3-5d8afec10557.png)

![Screenshot_2021-07-09-12-04-06-50](https://user-images.githubusercontent.com/75970303/125021865-0b183800-e0ae-11eb-91f3-04c5921adece.png)

**Comment by LANCECRAFT1104** [comment]
![Screenshot_2021-07-09-12-03-04-32](https://user-images.githubusercontent.com/75970303/125021838-fdfb4900-e0ad-11eb-82f3-5d8afec10557.png)

![Screenshot_2021-07-09-12-04-06-50](https://user-images.githubusercontent.com/75970303/125021865-0b183800-e0ae-11eb-91f3-04c5921adece.png)

WHAT THE HELL IS THAT MAN! I don't know how to apply PBR. I love PBR you know that?

**Comment by LANCECRAFT1104** [comment]
Teach me how to apply PBR.

**Comment by LANCECRAFT1104** [comment]
![Screenshot_2021-07-09-12-19-10-93](https://user-images.githubusercontent.com/75970303/125022733-eb820f00-e0af-11eb-8f02-f1f1ace9dec2.png)

I did this but not working.

**Comment by jebbyk** [comment]
Can you please try to reload minecraft?

**Comment by jebbyk** [comment]
@LANCECRAFT1104

**Comment by LANCECRAFT1104** [comment]
> Can you please try to reload minecraft?

Huh?

**Comment by LANCECRAFT1104** [comment]
Did you mean "Restart"?

**Comment by LANCECRAFT1104** [comment]
Oh, I just download the wrong version of Vanillaccurate.

**Comment by LANCECRAFT1104** [comment]
I can now close the issue THANK YOU ALL.
