### ISSUE TITLE
bug in swamp

### ISSUE THREAD

**Issue by Fajar-cv** [jebbyk/OSBES-minecraft-bedrock-edition-shader#189]
![Screenshot_2021-07-10-12-48-09-375_com mojang minecraftpe](https://user-images.githubusercontent.com/57588674/125162257-025c5a80-e1b1-11eb-9876-9c12d1235ae0.jpg)
how to fix it?
device redmi 9

**Comment by hope3x** [comment]
I've never seen a bug like this from anyone

**Comment by jebbyk** [comment]
@Fajar-cv can you please tell me mc version, seed and coordinates where you found this bug?

**Comment by jebbyk** [comment]
no answer from reporter. closing
