### ISSUE TITLE
The leaves gone wrong, turn to ugly

### ISSUE THREAD

**Issue by JUSTsean1118** [jebbyk/OSBES-minecraft-bedrock-edition-shader#191]
## Expected Behavior
since the minecraft have updated, all the leaves gone wrong, turn to a ugly block

## Current Behavior
 i think is because of new version? I really like your guys shaders, so i hope you guys can get this done quickly

**Comment by jebbyk** [comment]
@JUSTsean1118  can you please send some screenshots and tell which version of minecraft and OSBES you are using?

**Comment by JUSTsean1118** [comment]
Ok, im using v.17.0.50 beta version minecraft and version 1.5 osbes

**Comment by JUSTsean1118** [comment]
![a2253101690323eb438f0ca6693fc84](https://user-images.githubusercontent.com/87257270/125247995-23928780-e326-11eb-8ba5-257ae12c25ae.jpg)

**Comment by jebbyk** [comment]
@JUSTsean1118 ummmm... there is no such a version of OSBES :-). After looking at the screenshot I can say that you are using an outdated version of OSBES. try 0.13.1

**Comment by JUSTsean1118** [comment]
ok...
