### ISSUE TITLE
Some icons are bigger than normal when equipped with a texture pack regardless of the order.

### ISSUE THREAD

**Issue by RealNath** [jebbyk/OSBES-minecraft-bedrock-edition-shader#196]
Whenever I use both OSBES and MultiPixel (REGARDLESS OF THE TEXTURE PACK ORDER), some of the icons in UI look bigger than normal. But when I use 'only' OSBES or MultiPixel, the icons look normal.

## Expected Behavior
The icons are supposed to look normal.

## Current Behavior
Some icons look bigger than normal. The inventory UI also looks glitchy.
![Screenshot_20210717-163053690](https://user-images.githubusercontent.com/87565567/126032774-d8265e93-687c-41f9-9963-91e317d9e942.jpg)
![Screenshot_20210717-161712982](https://user-images.githubusercontent.com/87565567/126032776-d73e85e1-bfd9-48cd-9c06-dc2292159d35.jpg)
![Screenshot_20210717-161843016](https://user-images.githubusercontent.com/87565567/126032778-5900510d-3f44-4e05-b4a5-067891e8653e.jpg)

## Steps to Reproduce
Equip both MultiPixel and OSBES (regardless of OSBES being on top or bottom of MultiPixel)

**Comment by jebbyk** [comment]
should be fixed
