### ISSUE TITLE
Texture glitch again

### ISSUE THREAD

**Issue by Darthveder69420** [jebbyk/OSBES-minecraft-bedrock-edition-shader#199]
## Expected Behavior

Textures should look normal
## Current Behavior

Bugs is a bitch. Textures are corrupted on some servers and on some worlds but work fine on some other servers and worlds. This is a frequent occurrence on ios. I was using vanilla renewed too btw.
![D9F4E124-8879-47FA-AC5C-4D35422C98CE](https://user-images.githubusercontent.com/77436073/126456181-dc86ca0a-391c-4101-b9b8-68f5c8cade5a.png)

**Comment by jebbyk** [comment]
I will work on improving textures compatibility. Thanks :-)

**Comment by Darthveder69420** [comment]
:D

**Comment by jebbyk** [comment]
fixed
