### ISSUE TITLE
I can’t import the shader to minecraft [iPadOS]

### ISSUE THREAD

**Issue by MrOrange9-JCT** [jebbyk/OSBES-minecraft-bedrock-edition-shader#205]
## Expected Behavior
Open the file on the "Files" app and the shader sould import correctly to Minecraft

## Current Behavior
When I open the file it says: Importing packs… And when it finishes it says there is an error.

## Steps to Reproduce
Download the .mcpack file, open it, it should open minecraft. And then the error will happen.

![5AD44878-5BD7-4C23-AA42-E5A68F04106E](https://user-images.githubusercontent.com/66780535/127828155-48d232fd-d4d5-407c-b025-5850c543bd99.png)
![02728C06-31E8-49A2-A73D-E08CF8C5A539](https://user-images.githubusercontent.com/66780535/127828167-b3c911b4-9903-460c-ae4c-71c47af256cc.png)

**Comment by SamuraiKamikaze** [comment]
> ## Expected Behavior
> Open the file on the "Files" app and the shader sould import correctly to Minecraft
> 
> ## Current Behavior
> When I open the file it says: Importing packs… And when it finishes it says there is an error.
> 
> ## Steps to Reproduce
> Download the .mcpack file, open it, it should open minecraft. And then the error will happen.
> 
> ![5AD44878-5BD7-4C23-AA42-E5A68F04106E](https://user-images.githubusercontent.com/66780535/127828155-48d232fd-d4d5-407c-b025-5850c543bd99.png)
> ![02728C06-31E8-49A2-A73D-E08CF8C5A539](https://user-images.githubusercontent.com/66780535/127828167-b3c911b4-9903-460c-ae4c-71c47af256cc.png)

please close this, this error is common on iOS and iPadOS, Apple's file container is private and the game itself cannot access the file ... to import a .mcpack you must move it to the ipad / games / com.mojang / resource_packs, or first convert it to, zip and when you unzip it move it to that same folder

**Comment by jebbyk** [comment]
@SamuraiKamikaze ok thanks :-)
