### ISSUE TITLE
Glitchy blocks

### ISSUE THREAD

**Issue by Wheatman12** [jebbyk/OSBES-minecraft-bedrock-edition-shader#22]
There are many blocks that are glitchy, including oak planks, acacia planks, and anvils

**Comment by jebbyk** [comment]
Hi. Thank for feedback. Can you show some screenshots? And what is the game version and shader version you are using?

**Comment by Wheatman12** [comment]
Nevermind, it has been fixed on my end somehow. Now the textures are good.

**Comment by jebbyk** [comment]
ok then. Good news :-) I willl close the issue
