### ISSUE TITLE
Please do read this all!

### ISSUE THREAD

**Issue by UnknownMcUser** [jebbyk/OSBES-minecraft-bedrock-edition-shader#224]
(Issue made by UnknownMc_User)

Today i was looking through couple of issues like i always do cause im interested in seeing what other's have to say about this shader and then i went across this one person's issue witch was issued by SamuraiKamikaze and was issued on Jul the 26 i found this very unusual puddle disappearance while the lava was near another puddle

![127045030-c284db35-f63f-48ad-ae5e-f8b411db7ef5](https://user-images.githubusercontent.com/88826235/131105217-4fd213eb-a7a5-4649-9ff1-c7dbc0b718e1.png)

As you can see in the photo that SamuraiKamikaze made/took was very interesting to me if you look closely you can see that when the puddle is near the lava it disappears now let's look at the one's i took if you couldn't see it

![Screenshot_20210827-051939](https://user-images.githubusercontent.com/88826235/131105700-b1885176-b2a4-4410-b389-41624a03d9d5.png)

![Screenshot_20210827-052025](https://user-images.githubusercontent.com/88826235/131105730-ecdf496d-a4ca-4b9d-b62f-3fca471a8394.png)
Now here's the one's that i took so that you can see a bit better this is all i could mostly find but ill keep looking deep into what people didn't see or did see 

also i found this other weird bug or just lighting bug witch probably tons of people already know or don't entity's somehow glow in dark places or just outside mostly here's a photo

![Screenshot_20210827-052218](https://user-images.githubusercontent.com/88826235/131106398-5916f7af-2675-454b-991f-17c036620a38.png)

Now this is all i have for now

**Comment by UnknownMcUser** [comment]
The second photo was just showing how the lava in one block below doesn't effect the puddles near it but the puddles do seem to go onto the lava witch is still it the shader but i understand why so please keep trying you're best on making this shader the best!

**Comment by jebbyk** [comment]
@UnknownMcUser Imagine water evaporates near hot lava :-)

**Comment by UnknownMcUserbackupaccount** [comment]
> @UnknownMcUser Imagine water evaporates near hot lava :-)

I guess it makes sense also this is my back-up account

**Comment by SamuraiKamikaze** [comment]
> (Issue made by UnknownMc_User)
> 
> Today i was looking through couple of issues like i always do cause im interested in seeing what other's have to say about this shader and then i went across this one person's issue witch was issued by SamuraiKamikaze and was issued on Jul the 26 i found this very unusual puddle disappearance while the lava was near another puddle
> 
> ![127045030-c284db35-f63f-48ad-ae5e-f8b411db7ef5](https://user-images.githubusercontent.com/88826235/131105217-4fd213eb-a7a5-4649-9ff1-c7dbc0b718e1.png)
> 
> As you can see in the photo that SamuraiKamikaze made/took was very interesting to me if you look closely you can see that when the puddle is near the lava it disappears now let's look at the one's i took if you couldn't see it
> 
> ![Screenshot_20210827-051939](https://user-images.githubusercontent.com/88826235/131105700-b1885176-b2a4-4410-b389-41624a03d9d5.png)
> 
> ![Screenshot_20210827-052025](https://user-images.githubusercontent.com/88826235/131105730-ecdf496d-a4ca-4b9d-b62f-3fca471a8394.png) Now here's the one's that i took so that you can see a bit better this is all i could mostly find but ill keep looking deep into what people didn't see or did see
> 
> also i found this other weird bug or just lighting bug witch probably tons of people already know or don't entity's somehow glow in dark places or just outside mostly here's a photo
> 
> ![Screenshot_20210827-052218](https://user-images.githubusercontent.com/88826235/131106398-5916f7af-2675-454b-991f-17c036620a38.png)
> 
> Now this is all i have for now

Thank you for your support!

**Comment by jebbyk** [comment]
puddes in lava issue duplicate
