### ISSUE TITLE
Water Puddles

### ISSUE THREAD

**Issue by hope3x** [jebbyk/OSBES-minecraft-bedrock-edition-shader#225]
Water puddles ignore stairs.

![Screenshot_20210827-213155~3.png](https://user-images.githubusercontent.com/84674702/131160218-389afd41-769a-4bd9-bbfd-96ea5498f48b.png)![Screenshot_20210827-213241~2.png](https://user-images.githubusercontent.com/84674702/131160237-163c9579-b2c6-4ec6-8224-bade79228c91.png)

**Comment by UnknownMcUser** [comment]
What do mean by ignore stairs cause you took a picture that shows that the puddles are going on the stairs

**Comment by hope3x** [comment]
> What do mean by ignore stairs cause you took a picture that shows that the puddles are going on the stairs

Look at the second picture with the cover being closed. You can see the cobblestone being wet.

**Comment by UnknownMcUser** [comment]
> > What do mean by ignore stairs cause you took a picture that shows that the puddles are going on the stairs
> 
> Look at the second picture with the cover being closed. You can see the cobblestone being wet.

Oh

**Comment by jebbyk** [comment]
#202 duplicate
