### ISSUE TITLE
Entities are too bright and terrain is too dark at night when it's raining

### ISSUE THREAD

**Issue by shizotoaster** [jebbyk/OSBES-minecraft-bedrock-edition-shader#226]
If it's night and also it's raining, everything is too dark but entities
I suggest making rainy nights less dark but make mobs darker

## Expected Behavior

Normal ability to see things
## Current Behavior

I can see all of the entities but not the terrain
![image](https://user-images.githubusercontent.com/51480483/132372897-accf70c3-22f9-426e-90a0-c19751735911.png)

## Steps to Reproduce

Set night
Enable rain

**Comment by OpenSauce04** [comment]
This is being fixed in the next update

**Comment by jebbyk** [comment]
@OpenSauce04 you mean bright entities, not dark terrain, right?

**Comment by OpenSauce04** [comment]
Yeah
