### ISSUE TITLE
When I get closer to the leaves, I have drop frames, but when I move away from them, my frames are 60

### ISSUE THREAD

**Issue by MrNoBodyX5** [jebbyk/OSBES-minecraft-bedrock-edition-shader#227]

**Comment by MrNoBodyX5** [comment]
please how i can remove specular_mapping frome leaves only

**Comment by hope3x** [comment]
> please how i can remove specular_mapping frome leaves only 

By an editor??

**Comment by MrNoBodyX5** [comment]
> > please how i can remove specular_mapping frome leaves only
> 
> By an editor??
Acode editor

**Comment by hope3x** [comment]
> > > please how i can remove specular_mapping frome leaves only
> > 
> > By an editor??
> Acode editor

I'm talking about photo editors such as "Pixel Studio".

**Comment by jebbyk** [comment]
disable transparent leaves in game settings to improve performance
