### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by zeng-zeng367** [jebbyk/OSBES-minecraft-bedrock-edition-shader#228]
Will the 1.17.40.20 version be supported?

**Comment by amrmrni** [comment]
Unless mojang ads 3rd party shader support for render dragon it's no

**Comment by amisukarei** [comment]
> Will the 1.17.40.20 version be supported?

Unless mojang ads 3rd party shader support for render dragon it's no

**Comment by zeng-zeng367** [comment]
OK

**Comment by jebbyk** [comment]
it looks like even in. 1.18.xx it works normally
