### ISSUE TITLE
Shader not being applied and glitching

### ISSUE THREAD

**Issue by user9721** [jebbyk/OSBES-minecraft-bedrock-edition-shader#229]
when i add the shader to global resources it says loading texture packs but the loading screen flashes and when i reopen minecraft u get a grey screen

## Expected Behavior
 The shader should be applied. 

## Current Behavior
 the loading screen flashes and pack doesn't apple. When game is relaunched it shows a grey scren and doesnt open. 

## Steps to Reproduce

 im not sure how to do that. But the device i use is mi10i.

**Comment by hope3x** [comment]
Rename **.mcpack** to **.zip** and extract the stuff to resources_packs folder

**Comment by jebbyk** [comment]
@user9721 have you solved your problem?

**Comment by NathanDai5287** [comment]
Where is the resources_packs folder?

**Comment by jebbyk** [comment]
on answer, so I close this issue
