### ISSUE TITLE
Very thin texture gap between block boundaries

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#243]
## Expected Behavior

Blocks should render normally, with no gab between the textures:
![Screenshot_20211202-080730_Minecraft](https://user-images.githubusercontent.com/48618519/144382363-58f77a7b-94c0-47fa-9286-4f1d81ba7868.jpg)

## Current Behavior

There is a very small gap between textures; this only appears on the left/right side of the texture
![Screenshot_20211202-075816_Minecraft](https://user-images.githubusercontent.com/48618519/144382432-3f7262c3-288f-46e9-8302-a80c8095df3c.jpg)

## Steps to Reproduce

Load up vanilla OSBES 0.14.0, go to the side of a wall

**Comment by VAZaitesev** [comment]
issue #31 the same thing

**Comment by VAZaitesev** [comment]
@OpenSauce04 why I can't apply label on your issue tho? Have you any ideas?

**Comment by OpenSauce04** [comment]
> @OpenSauce04 why I can't apply label on your issue tho? Have you any ideas?

Why would you be able to?

**Comment by hope3x** [comment]
That's "padding" in **texture_terrain.json**. Changing it would only break texture packs you use. If you don't use a texture pack, you need to change the value to **1** instead of **0**.

**Comment by OpenSauce04** [comment]
> That's "padding" in **texture_terrain.json**. Changing it would only break texture packs you use. If you don't use a texture pack, you need to change the value to **1** instead of **0**.

That is so obscure that I didn't even know it existed

**Comment by hope3x** [comment]
> > That's "padding" in **texture_terrain.json**. Changing it would only break texture packs you use. If you don't use a texture pack, you need to change the value to **1** instead of **0**.
> 
> That is so obscure that I didn't even know it existed

┐( ∵ )┌

**Comment by jebbyk** [comment]
fixed
