### ISSUE TITLE
Strange boudaries between blocks on lower resolution texture packs with parallax mapping enabled

### ISSUE THREAD

**Issue by OpenSauce04** [jebbyk/OSBES-minecraft-bedrock-edition-shader#244]
## Expected Behavior
Blocks should smoothly transition from one to another

## Current Behavior
The texture of the blocks appears to "sink" between block boundaries

![image](https://user-images.githubusercontent.com/48618519/145195632-d037c9e2-dbfa-4f6c-a84e-cc777c98f5d3.png)

![Screenshot_20211209-065850_Minecraft.jpg](https://user-images.githubusercontent.com/48618519/145349341-be38f5bd-a1b9-44d6-8333-e664d8a1568a.jpg)

**Comment by OpenSauce04** [comment]
This might be related to issue #243

**Comment by OpenSauce04** [comment]
IMO fixing this should be a priority because it looks incredibly scuffed

**Comment by jebbyk** [comment]
that is why I moved compatibility block in roadmap almost to the top. I hope we will find out an effective way to correctly map textures even with texture paddings enabled. It will resolve all the "edges related" issues.

**Comment by jebbyk** [comment]
fixed
