### ISSUE TITLE
Does not have the new 1.18 items  affected by the shader

### ISSUE THREAD

**Issue by Battleknight07** [jebbyk/OSBES-minecraft-bedrock-edition-shader#246]
All I need is that you make the shader affects all the 1.18 items

**Comment by hope3x** [comment]
Shader won't work if you're using beta.

**Comment by hope3x** [comment]
Also, don't expect them to make something work right after something releases.

**Comment by OpenSauce04** [comment]
There weren't even any items added in 1.18 what are you on about

**Comment by jebbyk** [comment]
fixed. Now it depends only on texture pack used with a shader
