### ISSUE TITLE
Render Dragon Has Arrived

### ISSUE THREAD

**Issue by Fanzho666** [jebbyk/OSBES-minecraft-bedrock-edition-shader#247]
## Expected Behavior
I tried osbes and hope works well on beta

## Current Behavior
osbes didn't work and it has '[RENDER DRAGON]' on top of screen

![Screenshot_20211216-132203](https://user-images.githubusercontent.com/87934339/146319948-698c5aee-f50b-41dd-9e22-53ad5248c915.png)
![Screenshot_20211216-133754](https://user-images.githubusercontent.com/87934339/146320740-c0f7641a-5cfe-435f-9db9-1ff43a23b10e.png)

**Comment by hope3x** [comment]
Beta won't work... if you already know about the deal with renderdragon, why did you open an issue for it.

**Comment by Fanzho666** [comment]
I dont know anything i just hear a news of renderdragon but didn't know what is that

**Comment by hope3x** [comment]
> I dont know anything i just hear a news of renderdragon but didn't know what is that

It's an engine.
