### ISSUE TITLE
will this shader compilable on new Minecraft PE Render Dragon engine (on future update)

### ISSUE THREAD

**Issue by huhtel** [jebbyk/OSBES-minecraft-bedrock-edition-shader#248]
I like your shader so much not just because it make my minecraft have a fantasy graphic, also it can perform well on my phone maybe because you are doing quite well in optimization (btw my gpu is adreno 650 www). 
I heard the Microsoft Mojang will schedule a render engine update to Minecraft mobile(pocket edition) and it's called Render Dragon in later update (maybe 1.18.something or 1.19) many those 3rd party shader will be forbidden to run due to render dragon's pipeline...
(Ps: this is a question from me)

**Comment by huhtel** [comment]
> I like your shader so much not just because it make my minecraft have a fantasy graphic, also it can perform well on my phone maybe because you are doing quite well in optimization (btw my gpu is adreno 650 www). I heard the Microsoft Mojang will schedule a render engine update to Minecraft mobile(pocket edition) and it's called Render Dragon in later update (maybe 1.18.something or 1.19) many those 3rd party shader will be forbidden to run due to render dragon's pipeline... (Ps: this is a question from me)

**Comment by hope3x** [comment]
No, not until they do something.

**Comment by OpenSauce04** [comment]
Almost definitely not

**Comment by ThePrisonZombie** [comment]
Its too late, there are already minecraft beta 1.18.10.24 that implement the RenderDragon engine (this means at 1.19,there is no shader support [unless u downgrade to 1.18.2])

**Comment by huhtel** [comment]
i still using 1.18.1 hehe

**Comment by DownBeatGnu7882** [comment]
man i hate the fact that Minecraft made the game laggy after the 1.18 update.

**Comment by ThePrisonZombie** [comment]
U true. I hate RenderDragon, honestly
Since RenderDragon is coming to Minecraft WIN10,we cant use our shaders tho (playing on android)
