### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by NathanDai5287** [jebbyk/OSBES-minecraft-bedrock-edition-shader#249]
I downloaded the `.mcpack` file from the releases page and ran it. It opened Minecraft and the import started. 

The error message says `Failed to import OSBES-0.14.0.mcpack`. 

When I clicked on the message for more information, this showed up:
![image](https://user-images.githubusercontent.com/61402904/147622146-2921f9dc-7ca4-41a4-8f8b-efe6ef5b8f2f.png)

I tried renaming the file to something without any periods, but the same error occurred.

**Comment by FoxxeyPlays** [comment]
You have to rename it to a .zip file and then back to .mcpack

**Comment by Samuraiizzy** [comment]
I have the same issue and renaming to zip does not fix it for me.
