### ISSUE TITLE
Hey I wanted to use OSBES on my Oneplus6T but everything gone wrong:

### ISSUE THREAD

**Issue by MazeWave** [jebbyk/OSBES-minecraft-bedrock-edition-shader#25]
After applying the texture pack / shader from the main menu, the "tip" window thing starts blinking on the screen and Minecraft get basically stuck (softlock i think) (Epilepsy):
https://vimeo.com/481860007
After rebooting MCPE after force stopping it from the settings (just to be sure) the game block on a white screen after Mojang studio Logo and Minecraft Splash screen.
![White Screen](https://user-images.githubusercontent.com/25009364/99852275-f586ea00-2b80-11eb-972e-56d29af0026b.jpg)
Yeah I know the screenshot above don't help in any point xD

Minecraft Version : 1.16.100 (Nov,2,2020)
Device : Oneplus 6T | Android 10 | 8GB RAM

**Comment by jebbyk** [comment]
Is this problem happens only with my shaderpack or even with any other shader/texture package? what is the game version you are using?

**Comment by MazeWave** [comment]
only your shader :/

**Comment by jebbyk** [comment]
@MazeWave

**Comment by MazeWave** [comment]
> @MazeWave 

I just re-installed Minecraft and it works ¯\_(ツ)_/¯
But I didn't tested with the new game engine Render dragon.

**Comment by jebbyk** [comment]
coool :-) I closing this issue than
