### ISSUE TITLE
The problem is the lightning of the lantern it so bright

### ISSUE THREAD

**Issue by cyberops233** [jebbyk/OSBES-minecraft-bedrock-edition-shader#36]
![Screenshot_20201124_175633_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/74960700/100078457-7f370000-2e7e-11eb-8a84-667a176659de.jpg)

**Comment by jebbyk** [comment]
will think how to fix it. Thanks :-)

**Comment by jebbyk** [comment]
partially fixed
