### ISSUE TITLE
pink leaves in some places

### ISSUE THREAD

**Issue by jebbyk** [jebbyk/OSBES-minecraft-bedrock-edition-shader#37]
![image](https://user-images.githubusercontent.com/40975486/100187084-81966a00-2f11-11eb-84f9-3151e1424bdc.png)

**Comment by jebbyk** [comment]
dunno what is the biome

**Comment by btrhu** [comment]
I saw it too. Its the jungle leaves and the snow biome

**Comment by jebbyk** [comment]
fixed in 0.12.2
