### ISSUE TITLE
How do you fix this..

### ISSUE THREAD

**Issue by ShadowWolfieee** [jebbyk/OSBES-minecraft-bedrock-edition-shader#42]
Every time i use it(any version) this happens if your wondering what version i am its version 
![Screenshot_2020-11-25-20-43-43-65_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/75024923/100231282-c4802e00-2f61-11eb-92eb-ef19a75fe2bb.jpg)
1.16.200.55
![Screenshot_2020-11-25-20-54-09-39_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/75024923/100231298-ca760f00-2f61-11eb-9a24-6ae2213ca183.jpg)

**Comment by jebbyk** [comment]
Dont you using any kind of texturepack or addon adding new blocks with new textures? What is the version of the shader you are using?

**Comment by ShadowWolfieee** [comment]
I tried using all of them and its just the same thing every version, and no i only use the shader nothing else

**Comment by jebbyk** [comment]
dont you enable experimental gameplay or "faithfull" textures? IIt is very very strange.

**Comment by GETTHATBOIS** [comment]
I have kinda the same thing. It’s more of a texture than a shader

**Comment by jebbyk** [comment]
> I have kinda the same thing. It’s more of a texture than a shader

Is Experimental gameplay being enabled? If it is it can cause such problems

**Comment by GETTHATBOIS** [comment]
No I never have experimental gameplay on but just to make sure i will try it again. I will respond here once I finish.

**Comment by jebbyk** [comment]
thank you very much for your help

**Comment by jebbyk** [comment]
@ShadowWolfieee please make sure there is no add-ons ore texture packs are enabled globally or in the world you tested shader in. In the world where you want to play with osbes should not be textures or add-ons adding new textures at all. otherwise new added textures will damage textures from shaderpack.
