### ISSUE TITLE
fire texture

### ISSUE THREAD

**Issue by Happygaming232** [jebbyk/OSBES-minecraft-bedrock-edition-shader#43]
The fire texture seems to be broken. It doesn't animate at all on entities. And when you are on fire it does this...
![Screenshot_20201125-140444_Minecraft](https://user-images.githubusercontent.com/68204080/100281495-41da7d00-2f27-11eb-9253-31e30de62ce3.jpg)
![Screenshot_20201125-140422_Minecraft](https://user-images.githubusercontent.com/68204080/100281499-43a44080-2f27-11eb-9509-681f9e9bd7fd.jpg)

**Comment by Happygaming232** [comment]
I'm actually gonna record the entities problem

**Comment by Happygaming232** [comment]
[entities fire problem](https://drive.google.com/file/d/1071F7F2amvUO8RMCYV7VCFdfXsJlzDk7/view?usp=drivesdk)

**Comment by jebbyk** [comment]
Oh thanks. Haven noticed it. Will fix it asap

**Comment by jebbyk** [comment]
player fire fixed

**Comment by jebbyk** [comment]
will open separate issue about non animated burning entities fire.
