### ISSUE TITLE
Block textures messed up

### ISSUE THREAD

**Issue by bmt79** [jebbyk/OSBES-minecraft-bedrock-edition-shader#48]
I'm not too familiar with MCPE shaders, but it appears the normal maps are being mixed into the regular RGB textures on all the blocks (not items)

![Screenshot_20201126_214057_com mojang minecraftpe](https://user-images.githubusercontent.com/48388107/100393060-6a01d300-3030-11eb-8a91-a5a8cc20cf18.jpg)

![Screenshot_20201126_214356_com mojang minecraftpe](https://user-images.githubusercontent.com/48388107/100393122-856cde00-3030-11eb-8fc8-dd09e40c6352.jpg)

**Comment by jebbyk** [comment]
Make sure you are not using any custom texturepacks and any modification adding new blocks and textures.
What is the version of the game you are playing? What is the version of the shader? What is your device?

**Comment by GETTHATBOIS** [comment]
Great. Now I know I’m not the only one. Do you guys have a solution for this?

**Comment by jebbyk** [comment]
more information is needed

**Comment by jebbyk** [comment]
@BMT79 please make sure there is no add-ons ore texture packs are enabled globally or in the world you tested shader in. In the world where you want to play with osbes should not be textures or add-ons adding new textures at all. otherwise new added textures will damage textures from shaderpack.
