### ISSUE TITLE
Hard to play in survival..

### ISSUE THREAD

**Issue by Grub66** [jebbyk/OSBES-minecraft-bedrock-edition-shader#49]
Got a couple of things that should probably be fixed for a better overall experience first off this shader is the closest to java ever and is really good but jesus christ the torches do nothing in caves and mines can you please make them brighter, then the villagers are glitched and don’t show the right variations and clothing and certain mobs like snow golem have glitchy face, and finally its way to bright during day if you can tone it down a bit that would be nice. Thanks!!

**Comment by jebbyk** [comment]
ye. Some work with brightness presets is planned. Issues with snow golem is known and will be fixed.  Can you show some screenshots with glitched villagers?

**Comment by jebbyk** [comment]
will open separate issue about villagers if the issue will not gone
