### ISSUE TITLE
This shader is broken

### ISSUE THREAD

**Issue by GETTHATBOIS** [jebbyk/OSBES-minecraft-bedrock-edition-shader#52]
When I put this shader on my world it was completely broken. In fact it wasn’t even a shader. I took off all my texture packs but still didn’t work. It was a texture pack, not a shader. I don’t know what happened. It looked distorted and looked the exact opposite of what the pictures of the shader showed me. I would be really happy if you could fix this issue. Also I’m on iOS bedrock edition.

**Comment by jebbyk** [comment]
needs more details. screenshots maybe

**Comment by Happygaming232** [comment]
this might be due to either you not using the proper Shader/Game version, or your device isn't powerful enough for it.

**Comment by jebbyk** [comment]
im not sure that apple device can be not powerfull enough :-)

**Comment by Happygaming232** [comment]
which IPhone model are you using, and based on things I know, iOS has trouble with some Recource packs and will break them.

**Comment by jebbyk** [comment]
@GETTHATBOIS

**Comment by GETTHATBOIS** [comment]
I’m using iPad Pro. And it normally runs pretty good with no lag.

**Comment by jebbyk** [comment]
do you still getting the same problems? how much RAM do your device has? What the version of the game and of the shader?

**Comment by Happygaming232** [comment]
like I said, it might be due to not having the correct versions or iOS being annoying

**Comment by Happygaming232** [comment]
iPad pro is actually pretty outdated power wise

**Comment by GETTHATBOIS** [comment]
![FC00F7CD-7786-4D3F-85CC-7F0D1EAF3920](https://user-images.githubusercontent.com/75745084/103599898-2d998080-4ed4-11eb-95de-15137830a008.png)
Texture changed. Is this how it’s supposed to look like?

**Comment by Happygaming232** [comment]
kinda...
the fog/sky looks like it isn't rendering properly and some of the block maps too. Can you screenshot your graphic settings? It appears you have Beutiful skies and other things turned off. Most shaders packs are built with all the graphics settings enabled.

**Comment by GETTHATBOIS** [comment]
I always have the fancy settings on but I will check just in case

**Comment by Happygaming232** [comment]
![Screenshot_20210104-194406_Minecraft](https://user-images.githubusercontent.com/68204080/103600696-464e6a00-4ec5-11eb-816e-bf59f4b53f11.jpg)
you want your game to look more like this. 
I'd reccomend not using shades if you are hitting 30 fps or lower.

**Comment by GETTHATBOIS** [comment]
How do you check your FPS on mobile?

**Comment by Happygaming232** [comment]
one way is to just join the beta and an information thing shows up on the top. Or you are like me and can just tell based on how the game is running. I'd like to have you send me a recording of your game to see what you are dealing with. An image doesn't seem to help much. Thisll also help show how the lighting is working.

**Comment by jebbyk** [comment]
@GETTHATBOIS looks like you are playing with old version of osbes. i can see the sky light disappeared and clouds issue is not fixed. try to download zip just right from this repository, change file type from .zip to .mcpack and import it. And also I think your problem with textures was caused by add-ons applyed not globally but only for one of your world's where you have tested this shader.  So every time you see this kind of issue make sure there is no adddons or texture packs are enabled globally or in particularly world.

**Comment by GETTHATBOIS** [comment]
Ok I got it.
