### ISSUE TITLE
Some Nether suggestions/problems

### ISSUE THREAD

**Issue by Happygaming232** [jebbyk/OSBES-minecraft-bedrock-edition-shader#56]
A) Id think it'd be a good idea to make the Nether brighter. Currently it can be tricky to see in certain biomes such as the base one. I'd probably add this as a setting tho as some people won't mind. But since most people would be using their phone without the brightness all the way up they might not know what's what. 
![Screenshot_20210104-003647_Minecraft](https://user-images.githubusercontent.com/68204080/103512372-ccb36f00-4e25-11eb-85bb-42e71838d67b.jpg)
![Screenshot_20210104-003715_Minecraft](https://user-images.githubusercontent.com/68204080/103512376-cfae5f80-4e25-11eb-9ec6-35c3654b4a5d.jpg)

B) The nether portal effect is broken
![Screenshot_20210104-003604_Minecraft](https://user-images.githubusercontent.com/68204080/103512331-c0c7ad00-4e25-11eb-82e7-5f23acc5ea3a.jpg)

**Comment by jebbyk** [comment]
![Screenshot_20210104-135211](https://user-images.githubusercontent.com/40975486/103513145-35393500-4e94-11eb-959f-d6594a09467d.png)
can't get the same issue with portal

**Comment by Happygaming232** [comment]
this is when you go through the portal

**Comment by jebbyk** [comment]
![Screenshot_20210104-135937](https://user-images.githubusercontent.com/40975486/103513618-243cf380-4e95-11eb-8167-3ff30994cc5d.png)
it is ok for me too

**Comment by jebbyk** [comment]
wait. Are you talking about the lates version from gihub or about exact 0.11.1a ?

**Comment by Happygaming232** [comment]
that's a very good and important question

I am using exact 0.11.1a...

**Comment by jebbyk** [comment]
Im not sure but there is a chance that this issue was fixed with player fire issue  too just today. I just haven noticed this issue before because never statid to long in portals.

**Comment by Happygaming232** [comment]
looks like you fixed it in the version your using, but this is basically what I'm getting. 

https://drive.google.com/file/d/1HR-9nH6iSKI9YUIy7_PvPGD0AqrXXXd5/view?usp=drivesdk


(I was just thinking about the same reason of why it's fixed)

**Comment by jebbyk** [comment]
really haven noticed this issue before. Well I will not close this issue until not sure that it is gone in 0.11.2a
