### ISSUE TITLE
Upscaling

### ISSUE THREAD

**Issue by Happygaming232** [jebbyk/OSBES-minecraft-bedrock-edition-shader#58]
I don't know if this would be possible/ easy, but what if you upscale the textures to like 16 or 32 to get a smoother block map for certain blocks?

**Comment by jebbyk** [comment]
it is possible. and it is actually how the texture packs can be made for this shader. one guy just upscaled all the textures and then started to replace some of the upscaled textures with real hi res textures from other packs. it looks pretty good.

**Comment by jebbyk** [comment]
![image0](https://user-images.githubusercontent.com/40975486/103615654-26ff1d80-4f55-11eb-91ea-7ee197c66393.png)
like this

**Comment by jebbyk** [comment]
![Screenshot_20210105-131641](https://user-images.githubusercontent.com/40975486/103617401-63804880-4f58-11eb-9e65-2cfee3bb3e02.png)

**Comment by jebbyk** [comment]
![image0-1](https://user-images.githubusercontent.com/40975486/103617592-b823c380-4f58-11eb-935d-5cbe15c044b1.jpg)

**Comment by jebbyk** [comment]
texturepack related
