### ISSUE TITLE
Resource for Conduit is broken

### ISSUE THREAD

**Issue by SZ-Gamer** [jebbyk/OSBES-minecraft-bedrock-edition-shader#61]
Not sure if the Conduit is supposed to look this way. Other blocks seems fine.

![IMAGE 2021-01-18 11:33:22](https://user-images.githubusercontent.com/32050652/104872706-2c129280-5981-11eb-9dde-c5f9b3c548ec.jpg)

I'm not using any other resource packs.

![IMAGE 2021-01-18 11:45:17](https://user-images.githubusercontent.com/32050652/104873242-a42d8800-5982-11eb-8a72-c9c4e07fc6ba.jpg)

**Comment by jebbyk** [comment]
duplicate
