### ISSUE TITLE
When we go up high

### ISSUE THREAD

**Issue by sugawarome** [jebbyk/OSBES-minecraft-bedrock-edition-shader#62]
When we go up high. It will be like this. When look down the view everything turns white. 
![20B93524-07E3-413E-B3A6-4BCC6168B93F](https://user-images.githubusercontent.com/77873474/105570476-416e2f00-5d7c-11eb-8356-6728e9b60db6.png)

**Comment by jebbyk** [comment]
wow. Thank you!! Can you please tell me what is your device, what is the version of the game, and version of shader please :-)

**Comment by sugawarome** [comment]
> wow. Thank you!! Can you please tell me what is your device, what is the version of the game, and version of shader please :-)

My device’s iPhone 11 , game version is 1.16.201 and version of shader is 0.11.2 :)

**Comment by jebbyk** [comment]
thank you very much, will try to solve it asap :-)

**Comment by jebbyk** [comment]
probably fixed in 0.12.2
