### ISSUE TITLE
Textures are Weird

### ISSUE THREAD

**Issue by iiKhico** [jebbyk/OSBES-minecraft-bedrock-edition-shader#65]
Hi! So I got this pack and when I put it into my Minecraft world this happened:
![09F72740-444D-45B6-A611-9D582AB6607B](https://user-images.githubusercontent.com/78694929/107152166-5e862e80-6934-11eb-83f8-662d2bc75a31.png)
![EEE9B8EB-89B2-49EB-B22C-E76153CA24E6](https://user-images.githubusercontent.com/78694929/107152168-61811f00-6934-11eb-9954-3d9fdcab7055.png)

**Comment by NickGenghar** [comment]
By the looks of things, it appears that you have another texture pack loaded with the shader pack. OSBES is **incompatible** with any texture packs regardless of resource pack loading order. Try and remove the second texture pack and see if it resolves the issue.

**Comment by iiKhico** [comment]
Ok! I will try it again

**Comment by jebbyk** [comment]
@iiKhico so have you checked is it ok without addons and textures?
