### ISSUE TITLE
Conduit texture is bugged

### ISSUE THREAD

**Issue by Spaxel** [jebbyk/OSBES-minecraft-bedrock-edition-shader#66]
Conduit with Osbes

![Screenshot_2021-02-08-08-20-47-908_com mojang minecraftpe](https://user-images.githubusercontent.com/64981829/107274023-4098f680-6a26-11eb-88de-58a2292016d9.jpg)

Conduit with any other Shader

![Screenshot_2021-02-08-15-54-06-476_com mojang minecraftpe](https://user-images.githubusercontent.com/64981829/107274857-5e1a9000-6a27-11eb-9faa-6abaa486b787.jpg)

It's not critical, but it bothers a bit. Thank you!

**Comment by jebbyk** [comment]
partially fixed in 0.13.1 (this issue still happens when using PBR texture pack)
