### ISSUE TITLE
No texture packs, just the shader and this.

### ISSUE THREAD

**Issue by iiKhico** [jebbyk/OSBES-minecraft-bedrock-edition-shader#67]
![45779D96-66BE-4D10-9B11-4E0B10E06292](https://user-images.githubusercontent.com/78694929/107799367-51e64980-6d2b-11eb-8cb9-151fea090612.png)
![78EA11E7-CE4B-4766-822B-49ECC838D5B3](https://user-images.githubusercontent.com/78694929/107799378-54e13a00-6d2b-11eb-8ea6-9e7fec60e23a.png)
![1D90308D-FC58-47F8-B777-C38A9F0676F3](https://user-images.githubusercontent.com/78694929/107799388-57439400-6d2b-11eb-90f6-732e8d979898.png)

**Comment by jebbyk** [comment]
Make shure there is no addons applied to this world too

**Comment by iiKhico** [comment]
Yes, there isn’t any Addons

**Comment by CoadyKidd** [comment]
mine looks weird aswell heres a pic 
![image](https://user-images.githubusercontent.com/72046420/108883876-dd01f200-75fd-11eb-9434-5ec92a2fdd49.png)

**Comment by CoadyKidd** [comment]
its like half netherwart

**Comment by jebbyk** [comment]
@iiKhico @CoadyKidd can you guys pls try to reinstall minecraft, create new world without any add-ons and textures and try to use OSBES? I'll close issue for now but if reinstall didn't help you can reopen it
