### ISSUE TITLE
[Bug] Leaves of trees turn white and purple.

### ISSUE THREAD

**Issue by Marimarii485** [jebbyk/OSBES-minecraft-bedrock-edition-shader#68]
Some trees that are not in a snow biome are randomly white and don't wave. Sometimes they are colored purple. They do wave, but in the same manner as water.
![Screenshot_2021-02-13-16-09-26-272_com mojang minecraftpe](https://user-images.githubusercontent.com/79000635/107845508-e8dc0000-6e16-11eb-8a51-e0f545f065c4.jpg)
![Screenshot_2021-02-10-13-49-16-267_com mojang minecraftpe](https://user-images.githubusercontent.com/79000635/107845514-fb563980-6e16-11eb-9651-fc66ad3ec979.jpg)

**Comment by jebbyk** [comment]
duplicate
