### ISSUE TITLE
Random lines on floor and blocks when close to them  I am on iPhone XR

### ISSUE THREAD

**Issue by killerbot569** [jebbyk/OSBES-minecraft-bedrock-edition-shader#79]
![CAF3C5C4-2431-4347-AE1C-302A39DA770D](https://user-images.githubusercontent.com/79696280/109288923-66dbd600-781d-11eb-87e0-4ecdd8c3a246.png)
![4F884295-0C88-43FF-8682-C19C86779F43](https://user-images.githubusercontent.com/79696280/109288933-6b07f380-781d-11eb-9806-dc2c736bc6e8.png)

**Comment by jebbyk** [comment]
fixed in 0_12_2

**Comment by killerbot569** [comment]
How do I download 0.12.2
