### ISSUE TITLE
If I leave the world and return the shader changes the appearance of blocks

### ISSUE THREAD

**Issue by FrenchyFrys01** [jebbyk/OSBES-minecraft-bedrock-edition-shader#80]
If I save and quit when returning to the world leaving shaders on the appearances of block changes like a texture swap
![7E4BDFB2-CD5C-457E-9318-931AEBF8965B](https://user-images.githubusercontent.com/79721136/109346620-f4c8b880-783f-11eb-875b-f9eb1c07ba14.png)
![196A8721-68A2-4793-B5D8-5764EA27B78D](https://user-images.githubusercontent.com/79721136/109346630-f6927c00-783f-11eb-9e15-51072ced3771.png)
![25426E48-212A-4969-A1E9-27549F917717](https://user-images.githubusercontent.com/79721136/109346637-f85c3f80-783f-11eb-999f-55b7be0bd9bf.png)
![1DE026B4-40B0-47BA-9CAC-6E8DB9F6AC3F](https://user-images.githubusercontent.com/79721136/109346641-f8f4d600-783f-11eb-945c-677d9404dc52.png)
![21A788CA-9ABD-41B1-9F1A-B3EC5C1AEB40](https://user-images.githubusercontent.com/79721136/109346644-f98d6c80-783f-11eb-950e-2ebb1173e7b1.png)

**Comment by jebbyk** [comment]
@FrenchyFrys01  If you just reload minecraft is it ok?

**Comment by jebbyk** [comment]
looks like it is not related to the shaderpack. It is more like that it is related to the logic of loading texturepacks and addons

**Comment by jebbyk** [comment]
probably can be closed
