### ISSUE TITLE
Rain glitch

### ISSUE THREAD

**Issue by Randomerjaden** [jebbyk/OSBES-minecraft-bedrock-edition-shader#85]
Weird rain glitch that makes everything look black. I'm not sure if it's intentional or not but it makes OSBES unplayable in rain/thunder. Before 0.12.1a Rain/thunder did not have this "black effect" It just darkened the sky a little bit and added puddles. Maybe try to lighten up the sky when 0.12.2a comes out. :)

**Comment by jebbyk** [comment]
@Randomerjaden if it happens at night time than it is ok. if in day time than probably it is a bug. Can you please send some screenshots?

**Comment by Randomerjaden** [comment]
This happens in day and night currently it is day in the photo
![332892C2-326C-4264-BFB1-7042615A796D](https://user-images.githubusercontent.com/79774752/110249794-8a013680-7f3d-11eb-81e8-baf3214f9986.jpeg)

**Comment by jebbyk** [comment]
it is probably already fixed in 0.12.2. wait for update and if it is not fixed reopen this issue.
