### ISSUE TITLE
Broken Grass Block Item Texture

### ISSUE THREAD

**Issue by ghost** [jebbyk/OSBES-minecraft-bedrock-edition-shader#86]
When a grass block is in your inventory, hotbar, or hand, the dirt portion of the texture is all black and it only shows the grass overlay.
![osbes_grass_bug](https://user-images.githubusercontent.com/62409275/110226885-b1fe8480-7ec0-11eb-81ad-681de3b3f5f0.png)

**Comment by jebbyk** [comment]
since you can use grass block only in creative I'll put "not critical" label on this issue.

**Comment by jebbyk** [comment]
fixed by BambooSapling
