### ISSUE TITLE
Wierd rendering of some things in inventory

### ISSUE THREAD

**Issue by FilipBalcarek** [jebbyk/OSBES-minecraft-bedrock-edition-shader#91]
Some things in inventory are wierd rendering, like grass block is black, rails are connected with some other items.
![Screenshot_20210313-115132~2](https://user-images.githubusercontent.com/80578420/111028039-46527500-83f4-11eb-96fc-aeb6b88304c8.png)
![Screenshot_20210313-115123~2](https://user-images.githubusercontent.com/80578420/111028044-4e121980-83f4-11eb-96db-afb057517d06.png)
![Screenshot_20210313-114752~2](https://user-images.githubusercontent.com/80578420/111028046-536f6400-83f4-11eb-85c7-00198060f3a9.png)
![Screenshot_20210313-114739~2](https://user-images.githubusercontent.com/80578420/111028049-59654500-83f4-11eb-9b52-dfbc1fa2a5fb.png)

**Comment by fiyingsheep** [comment]
The sweet berries are also way smaller

**Comment by jebbyk** [comment]
this issue probably is not fixable

**Comment by Clowngod1231** [comment]
At least try because I get into a world on Minecraft annnd this keeps happening. 
![46D069C4-FED1-41E8-90DB-BAA5CA786AFD](https://user-images.githubusercontent.com/87597468/126059637-5c7c3986-288a-4374-859f-0651f6dddaca.png)

**Comment by SamuraiKamikaze** [comment]
![D73B321B-639D-460E-898A-803D0F6457AE](https://user-images.githubusercontent.com/87953001/127439990-ed311a37-e4b1-4eb5-a610-6b864d3a5c13.jpeg)

**Comment by FilipBalcarek** [comment]
fixed in 0.13.2
