### ISSUE TITLE
Weird texture

### ISSUE THREAD

**Issue by noobdeveloper-lang** [jebbyk/OSBES-minecraft-bedrock-edition-shader#95]
Texture becoming weird on some China device
Tested on Oppo A3s,Realme C3
![Screenshot_2021-03-17-17-25-23-46](https://user-images.githubusercontent.com/74964564/111733831-61692d00-88ab-11eb-8ba5-6db040c2366a.png)

**Comment by jebbyk** [comment]
@noobdeveloper-lang Hey. Please try to create new world without any texturepacks or addons enabled globaly or locally :-)
