### ISSUE TITLE
Rain bug

### ISSUE THREAD

**Issue by Randomerjaden** [jebbyk/OSBES-minecraft-bedrock-edition-shader#97]
This bug has still not been fixed the bug made everything white instead of dark it is day in the photo 
![24A96E12-D470-4120-87A3-7125F3CEF59D](https://user-images.githubusercontent.com/79774752/112574216-deb90400-8dbb-11eb-9c86-4297d5862360.png)

**Comment by jebbyk** [comment]
fixed in upcoming 0.12.3 hotfix
