### ISSUE TITLE
Water parallax issue

### ISSUE THREAD

**Issue by Randomerjaden** [jebbyk/OSBES-minecraft-bedrock-edition-shader#98]
I noticed when I was swimming around the water parallax kept turning off and on i noticed it was in specific areas 
![7070EDA2-77E6-436F-9395-FA34736396BD](https://user-images.githubusercontent.com/79774752/112574657-c4cbf100-8dbc-11eb-8b5e-5ac44818acfa.png)

**Comment by jebbyk** [comment]
probably fixed
